//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NascarRaceManagment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceUser
    {
        public int Id { get; set; }
        public int RaceId { get; set; }
        public int UserId { get; set; }
    
        public virtual Race Race { get; set; }
        public virtual User User { get; set; }
    }
}
